### ISSUE TITLE
FontAwesome >= 5.7 support

### ISSUE THREAD

**Issue by olbat** [FA-Minify/fa-minify#1]
It seems that the library does not work properly with FontAwesome >= 5.7, am I wrong?

**Comment by NetWin** [comment]
yeah it seems like you're right. I'll fix it 👍

**Comment by olbat** [comment]
Awesome! Thanks a lot 😄

**Comment by NetWin** [comment]
fixed it: https://www.npmjs.com/package/fa-minify
Also i adjusted my version to Font Awesome. 
So my 5.8.1 does support at least FA@5.8.1 (but tested it with 5.7.0 too).

Have Fun 😁

**Comment by olbat** [comment]
Wow that was fast! 😮

Thank you for the fast upgrade as well as for your awesome work on this project 👍

**Comment by NetWin** [comment]
you‘re welcome 👍🏼
when you have any problems or suggestions, 
feel free to open a new issue 😁
